In [5]:
import requests
import pandas as pd

token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRlIjoiMjAyNS0wMi0wNCAxMzoyOTo0MyIsInVzZXJfaWQiOiJyYXVsaHNpYW8iLCJpcCI6IjYxLjY2Ljc5LjE4IiwiZXhwIjoxNzM5MjUxNzgzfQ.Lzax57JTqKX39EiGAnkyYScPj0OpdWTqNKaXfFT9fxE"

url = 'https://api.finmindtrade.com/api/v4/taiwan_stock_warrant_trading_daily_report'
parameter = {
    "data_id": "0050",
    "date": "2025-02-04",
    "token": token, # 參考登入，獲取金鑰
}
data = requests.get(url, params=parameter)
data = data.json()
data = pd.DataFrame(data['data'])
data[:20]

Empty DataFrame
Columns: []
Index: []

In [22]:
from FinMind.data import DataLoader

api = DataLoader()
api.login_by_token(api_token=token)
# api.login(user_id='user_id',password='password')
df = api.taiwan_stock_government_bank_buy_sell(
    start_date='2025-01-03',
)
df

2025-02-04 16:01:05.973 | INFO     | FinMind.data.finmind_api:get_data:148 - download Dataset.TaiwanStockGovernmentBankBuySell, data_id:

             date stock_id   buy_amount  sell_amount    buy    sell bank_name
0      2025-01-03     0050  11935634.75  24218602.20  60861  123414        兆豐
1      2025-01-03     5452   1941930.10   1128200.00  61093   36000        第一
2      2025-01-03     5452    231201.00    222550.00   7290    7000        臺銀
3      2025-01-03     5452    792332.60     96831.55  25001    3001        華南
4      2025-01-03     5455         0.00     58900.00      0    1000        臺銀
...           ...      ...          ...          ...    ...     ...       ...
11954  2025-01-03     2608         0.00     38800.00      0    1000        合庫
11955  2025-01-03     2608    162640.00     38750.00   4200    1000        第一
11956  2025-01-03     2608      2786.80     77743.00     72    2005        臺銀
11957  2025-01-03     2607    315872.60    157000.00  10069    5000        兆豐
11958  2025-01-03     9962     28900.00    219596.00   2000   15010        華南

[11959 rows x 7 columns]

In [27]:
from FinMind.data import DataLoader

api = DataLoader()
api.login_by_token(api_token=token)
# api.login(user_id='user_id',password='password')
df = api.taiwan_stock_trading_daily_report_secid_agg(
    stock_id="0050",
    securities_trader_id="1020",
    start_date= "2021-06-30",
    end_date="2025-02-03",
)
df

2025-02-04 17:43:38.833 | INFO     | FinMind.data.finmind_api:get_data:148 - download Dataset.TaiwanStockTradingDailyReportSecIdAgg, data_id: 0050

,securities_trader,securities_trader_id,stock_id,date,buy_volume,sell_volume,buy_price,sell_price
0,合庫,1020,0050,2021-06-30,1360,16000,139.16,138.84
1,合庫,1020,0050,2021-07-01,181623,751030,138.89,138.95
2,合庫,1020,0050,2021-07-05,26314,7660,138.98,139.63
3,合庫,1020,0050,2021-07-06,9320,2000,139.75,139.85
4,合庫,1020,0050,2021-07-07,3800,150,139.03,139.05
...,...,...,...,...,...,...,...,...
858,合庫,1020,0050,2025-01-17,16301,100,195.66,196.50
859,合庫,1020,0050,2025-01-20,36761,17131,198.24,198.20
860,合庫,1020,0050,2025-01-21,5370,1352,198.14,198.55
861,合庫,1020,0050,2025-01-22,193200,201570,201.43,200.34
862,合庫,1020,0050,2025-02-03,160748,21933,192.00,191.89